name: Nix CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./nixos

env:
  NIX_PATH: nixpkgs=channel:nixos-25.05

jobs:
  electron:
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Check out repository
        uses: actions/checkout@v4

      - &nix-install
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - &nix-cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Build Electron in Nix
        run: nix-build -A electron

  rust:
    runs-on: ubuntu-latest

    steps:
      - *checkout
      - *nix-install
      - *nix-cache

      - name: Build Electron in Nix
        run: nix-build -A server
