name: Nix CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NIX_PATH: nixpkgs=channel:nixos-25.05

defaults:
  run:
    working-directory: ./nixos

jobs:
  electron:
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Check out repository
        uses: actions/checkout@v4

      - &nix-install
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - &nix-cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Build Electron in Nix
        run: nix-build -A electron

      - &nix-store-add
        name: Add to Nix Store
        run: nix-store --realize --add result

  rust:
    runs-on: ubuntu-latest

    steps:
      - *checkout
      - *nix-install
      - *nix-cache

      - name: Build Server in Nix
        run: nix-build -A server

      - *nix-store-add

  format:
    runs-on: ubuntu-latest

    steps:
      - *checkout
      - *nix-install

      - name: Format
        working-directory: ./
        run: nix run 'nixpkgs#nixfmt-classic' $(find . nixos -name '*.nix')

  check:
    runs-on: ubuntu-latest

    steps:
      - *checkout
      - *nix-install

      - name: Build Flake and Configuration.nix
        run: nix flake check "." --impure

  build:
    runs-on: ubuntu-latest
    needs: [electron, rust]

    steps:
      - *checkout
      - *nix-install
      - *nix-cache

      - name: Build Flake and Configuration.nix
        working-directory: ./
        run: nix build "."

      - *nix-store-add
